# Generated by Django 3.2.7 on 2021-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_create_demo_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageblock",
            options={
                "ordering": ["custom_order"],
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
            },
        ),
        migrations.AddField(
            model_name="pageblock",
            name="custom_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
