# Generated by Django 3.2.7 on 2021-09-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_block_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.page', verbose_name='Страница'),
        ),
    ]
