# Generated by Django 3.2.7 on 2021-09-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_block_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='content_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.audiocontent', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='content_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.textcontent', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='content_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.videocontent', verbose_name='Видео'),
        ),
    ]
